/**
 * Trackless ingest wire-protocol types.
 *
 * VERBATIM COPY of packages/shared-types/src/ingest.ts, which is the canonical
 * source. Duplicated here so the published sdk-web package stays dependency
 * free: @trackless/shared-types is an unpublished workspace package and cannot
 * resolve outside the monorepo, which previously broke `tsc` in the standalone
 * repo and shipped a dangling type import to consumers.
 *
 * Only the wire protocol is copied — never the rest of @trackless/shared-types
 * (billing tiers, auth/waitlist, dashboard analytics, app records), which is
 * internal and must not ship in a public package.
 *
 * Do not edit this file. Edit shared-types/src/ingest.ts and re-copy;
 * packages/shared-types/__tests__/wire-copy.test.ts fails if the two diverge.
 */
export type EventType = "session" | "view" | "feature" | "funnel" | "performance" | "error";

export type ErrorSeverity = "debug" | "info" | "warning" | "error" | "fatal";

export type Platform = "ios" | "android" | "web";

export type DeviceClass = "phone" | "tablet" | "desktop" | "watch" | "tv" | "unknown";

export type Browser = "chrome" | "safari" | "firefox" | "edge" | "bot" | "other";

export type Os = "macos" | "windows" | "linux" | "android" | "ios" | "other";

export type Environment = "sandbox" | "production";

/** Device/app context sent with each event payload */
export interface EventContext {
  appVersion?: string;
  buildNumber?: string;
  platform?: Platform;
  /** Major version only (e.g. "17", "15") */
  osVersion?: string;
  deviceClass?: DeviceClass;
  region?: string;
  language?: string;
  browser?: Browser;
  os?: Os;
  /** SDK platform and version (e.g., "web/0.2.5", "ios/0.2.3") */
  sdkVersion?: string;
  /** Distribution channel (e.g., "testflight", "app_store", "play_store", hostname for web) */
  distributionChannel?: string;
  daysSinceInstall?: number;
}

/**
 * Individual event in a batch.
 *
 * Type-specific fields:
 * - `count`: defaults to 1 if omitted. SDKs set count > 1 when client-side rollup collapses duplicates.
 * - `firstUses`: feature events only. Once-per-session first-use marker (1 <= firstUses <= count).
 * - `detail`: optional detail value for view and feature events (e.g., view("product", "shoes")).
 * - `step` / `stepIndex`: funnel events only.
 * - `duration`: single performance measurement. Mutually exclusive with `durations`.
 * - `durations`: multiple performance measurements from client-side rollup. Mutually exclusive with `duration`.
 * - `threshold`: optional performance threshold in seconds. Creates a separate row per name/threshold combo.
 * - `severity` / `code`: error events only.
 */
export interface TracklessEvent {
  type: EventType;
  name: string;
  count?: number;
  firstUses?: number;
  detail?: string;
  step?: string;
  stepIndex?: number;
  duration?: number;
  durations?: number[];
  threshold?: number;
  severity?: ErrorSeverity;
  code?: string;
}

/** Full event payload from SDK */
export interface EventPayload {
  date: string;
  environment?: Environment;
  context: EventContext;
  events: TracklessEvent[];
}

/** Ingest response */
export interface IngestResponse {
  accepted: number;
  rejected: number;
  errors?: Array<{ index: number; reason: string }>;
}
